name: Aan mijzelf
description: Overpeinzingen, over van alles en nog wat
meta_description: "Overpeinzingen, over van alles en nog wat.."  
markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://niek33.github.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'

