name: Kantoortijger
description: Gereedschap voor de ambitieuze kantoortijger
meta_description: "Gereedschap voor de ambitieuze kantoortijger"  
markdown: kramdown
highlighter: rouge
logo: false
paginate: 5
baseurl: 'http://www.kantoortijger.nl'
domain_name: 'http://kantoortijger.github.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'

