name: Aan mijzelf
description: Overpeinzingen, gedachtespinsels en mentale notities
meta_description: "Overpeinzingen, gedachtespinsels en mentale notities.."  
markdown: kramdown
highlighter: rouge
logo: false
paginate: 5
baseurl: 'http://www.aanmijzelf.nl'
domain_name: 'http://niek33.github.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'

